env:
  global:
    - NODE_ENV=test
language: node_js
node_js:
  - 'stable'
install: npm install
services:
  - mongodb
cache:
  directories:
    - 'node_modules'
before_script:
  - sleep 15
  - mongo peng_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script: npm test
notifications:
  email: false
